Add menus
toryjleo/BikeIdea pull request #125
Opened 2023-09-16 13:59 UTC by Jomkit

Pushing my progress as requested

2023-09-16 16:46 UTC, toryjleo commented on Assets/Scripts/UI/ButtonTest.cs
> +public class ButtonTest : MonoBehaviour
Could you change the name of this class to something that makes a bit more sense? Is this the main menu?

2023-09-16 16:46 UTC, toryjleo commented on Assets/Scripts/UI/PauseMenu.cs
> +        Time.timeScale = 0f;
Could you please remove the timescale changes? Pausing the game time causes bugs.

2023-09-16 16:46 UTC, toryjleo commented on Assets/Scripts/UI/PauseMenu.cs
> +        Debug.Log("Quitting Game...");
Please add Quitting functionality

2023-09-16 16:46 UTC, toryjleo commented on Assets/Scripts/UI/ButtonTest.cs
> +    private void fuck()
Remove fuck function

2023-09-16 16:46 UTC, toryjleo commented on Assets/Scripts/UI/ChangeScene.cs
> +public class ChangeScene : MonoBehaviour
What is changescene? Could you add a class description?

example: https://github.com/toryjleo/BikeIdea/blob/master/Assets/Scripts/Player/BikeScript.cs#L8-L9

2023-09-23 09:17 UTC, Jomkit commented on Assets/Scripts/UI/ButtonTest.cs
> +public class ButtonTest : MonoBehaviour
This was just a script for testing button press, I'm gonna remove it

2023-09-23 09:53 UTC, Jomkit commented on Assets/Scripts/UI/PauseMenu.cs
> +        Time.timeScale = 0f;
I can remove it, but I'm not sure what to replace it with to enable the game to pause when bringing the pause menu up

2023-09-23 14:49 UTC, LiamMillerSE approved these changes

2023-09-30 15:56 UTC, toryjleo requested changes
- [ ] Update Main Menu button alignment
 - [ ] Remove changes to TrueScene
 - [ ] Merge with Liam's branch
 - [ ] Add back PauseMenu blueprint

2023-10-01 12:52 UTC, LiamMillerSE commented
Play and Quit buttons are high and locked to the sides, when I maximize the game, the buttons are off the top of the screen

2023-10-01 13:15 UTC, LiamMillerSE approved these changes

2023-10-01 13:15 UTC, toryjleo approved these changes

2023-10-01 13:15 UTC, merged