Final Commit for Waves beta
toryjleo/BikeIdea pull request #126
Opened 2023-09-23 14:27 UTC by LiamMillerSE

Implemented:
Waves have sets of squads to spawn in
Waves have trackvariants associated with them
5 Tracks and their associated Wave Sequences
Enemies have a dlScore that increases the danger level by that amount when the enemy is killed DLevel is now properly an IResettable

Modified:
Danger Level now decreases steadily instead of increases Squads are now spawned by the WaveSequence/Jukebox objects instead of just on a timer

Fixed:
Squad manager cleans up after itself better

Removed:
Some annoying Debug Logs

2023-09-23 14:59 UTC, toryjleo requested changes

2023-09-23 14:59 UTC, toryjleo commented on Assets/Scripts/SceneManageMent/Waves/Wave.cs
> +
Give brief description of class

2023-09-23 14:59 UTC, toryjleo commented on Assets/Scripts/SceneManageMent/Waves/WaveSequence.cs
> +/// A track is a container of all associated music clips.
We need to nail down nomenclature. Is this a track or a WaveSequence?

2023-09-23 14:59 UTC, toryjleo commented on Assets/Scripts/SceneManageMent/Waves/WaveSequence.cs
> +/// A track is a container of all associated music clips.
It might also be a container of tracks?

2023-09-23 14:59 UTC, toryjleo commented on Assets/Scripts/SceneManageMent/Waves/WaveSequence.cs
> +        //if (CurrentWave >= previousWave || CurrentWave < previousWave - 1)
Do we use this conditional?

2023-09-23 14:59 UTC, toryjleo commented on Assets/Scripts/SceneManageMent/Waves/WaveSequence.cs
> +        int index = 0;
Could you place this inside the for-loop and do the "CurrentWave = index;: calculation before the break>

2023-09-23 14:59 UTC, toryjleo commented on Assets/Scripts/SceneManageMent/Waves/WaveSequences.meta
> +fileFormatVersion: 2
Could we move the "Wave Sequences" out of "Scripts"? We should have some sort of folder specifically for game assets that are not scripts and impact gameplay or levels

2023-09-23 14:59 UTC, toryjleo commented on Assets/Scripts/SceneManageMent/Waves/Wave.cs
> +    public int DLThreshold;
Please add comment

2023-09-23 14:59 UTC, toryjleo commented on Assets/Scripts/Audio/Jukebox.cs
> +    public List<WaveSequence> soundTracks;
Please comment variables

2023-09-23 14:59 UTC, toryjleo commented on Assets/Scripts/Audio/Jukebox.cs
> +        //// TODO: Make dynamic
Is this TODO a ticket?

2023-09-23 14:59 UTC, toryjleo commented on Assets/Scripts/SceneManageMent/Waves/WaveSequence.cs
> +/// A track is a container of all associated music clips.
A description of the relationship between waves and danger level might fit well here

2023-09-26 12:32 UTC, LiamMillerSE commented on Assets/Scripts/Audio/Jukebox.cs
> +        //// TODO: Make dynamic
No, this TODO was part of old code, the commented part's functionality got moved to WaveSequence

2023-09-26 12:36 UTC, LiamMillerSE commented on Assets/Scripts/SceneManageMent/Waves/WaveSequences.meta
> +fileFormatVersion: 2
Moved folder to prefabs/Audio

2023-09-26 13:16 UTC, toryjleo requested changes
Further changes I would like to see before merge:
- [ ] All unimplemented enemy enums commented out
- [x] A working, progressing wave sequence in the jukebox

2023-10-01 12:51 UTC, toryjleo requested changes
Getting error:
ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index
System.ThrowHelper.ThrowArgumentOutOfRangeException (System.ExceptionArgument argument, System.ExceptionResource resource) (at <eae584ce26bc40229c1b1aa476bfa589>:0)
System.ThrowHelper.ThrowArgumentOutOfRangeException () (at <eae584ce26bc40229c1b1aa476bfa589>:0)
System.Collections.Generic.List`1[T].get_Item (System.Int32 index) (at <eae584ce26bc40229c1b1aa476bfa589>:0)
Jukebox.Start () (at Assets/Scripts/Audio/Jukebox.cs:24)

2023-10-01 12:57 UTC, toryjleo approved these changes

2023-10-01 13:04 UTC, merged