Turret merge
toryjleo/BikeIdea pull request #48
Opened 2022-06-01 23:12 UTC by Tomerd-afk

Added new bike prefabs and ai fixes/rebalancing.

2022-06-01 23:27 UTC, toryjleo requested changes

2022-06-01 23:27 UTC, toryjleo commented on Assets/Scripts/Player/TurretScript.cs
> +public class TurretScript : Gun
Please add a summary of class

2022-06-01 23:27 UTC, toryjleo commented on Assets/Scripts/Player/BikeScript.cs
> +        turret = GetComponentInChildren<TurretScript>();
This assumes all bikes have a turret. I think this would break the non-turret gameObject. Please add another child class or make this not dependent on turret

2022-06-01 23:48 UTC, Tomerd-afk commented on Assets/Scripts/Player/TurretScript.cs
> +public class TurretScript : Gun
Added

2022-06-01 23:49 UTC, Tomerd-afk commented on Assets/Scripts/Player/BikeScript.cs
> +        turret = GetComponentInChildren<TurretScript>();
I changed it to an if statement, I also added an if statement for when the turret is firing.

2022-06-01 23:51 UTC, toryjleo submitted a review, later dismissed

2022-06-04 13:17 UTC, toryjleo approved these changes

2022-06-05 00:16 UTC, toryjleo requested changes
This branch caused a bug.
Build does not allow for Bike to collide with calendars and enemy bullets move slow.

2022-06-05 14:54 UTC, toryjleo commented on Assets/Materials/BikeLightEmissive.mat
> -    - _EmissionSlider: 0.76292205
why is this updated? Is this part of your change?

2022-06-05 23:59 UTC, Tomerd-afk commented on Assets/Materials/BikeLightEmissive.mat
> -    - _EmissionSlider: 0.76292205
No idea, It keeps getting updated

2022-06-06 00:07 UTC, toryjleo approved these changes

2022-06-06 00:13 UTC, merged