Disposable weapons Merge
toryjleo/BikeIdea pull request #60
Opened 2022-06-21 22:44 UTC by LiamMillerSE

Added Vulkan V64 Autocannons
Gave ability to grant players weapons after certain score threshold is reached
Guns now have ammo. When the current gun runs out of ammo, player goes back to their default gun
Bullets can now have conditions. Conditions are effects that can do things like damage over time to enemies

2022-06-21 22:56 UTC, toryjleo reviewed
Additionally I get an error when running the scene:

NullReferenceException: Object reference not set to an instance of an object
BikeScript.EquipGun (Gun gunToEquip) (at Assets/Scripts/Player/BikeScript.cs:133)
BikeScript.InitializeStartingGun () (at Assets/Scripts/Player/BikeScript.cs:145)
BikeScript.Awake () (at Assets/Scripts/Player/BikeScript.cs:76)

2022-06-21 22:56 UTC, toryjleo commented on Assets/Scripts/Bullets/VulkanV64Trail.cs
> +        Debug.Log("VULKAN FIRE!");
Please comment out Debug statements for master

2022-06-21 22:56 UTC, toryjleo commented on Assets/Scripts/Bullets/VulkanV64Trail.cs
> +    private IEnumerator SpawnTrail(TrailRenderer trail, Vector3 endLoc)
Please comment

2022-06-21 22:56 UTC, toryjleo commented on Assets/Scripts/Conditions/Burning.cs
> +public class Burning : Condition
Please comment class summary

2022-06-21 22:56 UTC, toryjleo commented on Assets/Scripts/Conditions/Condition.cs
> +public abstract class Condition : MonoBehaviour
Please comment class summary

2022-06-21 22:56 UTC, toryjleo commented on Assets/Scripts/Conditions/Condition.cs
> +    public void Tick()
Please comment method summary

2022-06-21 22:56 UTC, toryjleo commented on Assets/Scripts/Conditions/Condition.cs
> +    public void SetHostAi(Ai host)
Ditto

2022-06-21 22:56 UTC, toryjleo commented on Assets/Scripts/Guns/GunCrate.cs
> +public class GunCrate : MonoBehaviour
Ditto

2022-06-21 22:56 UTC, toryjleo commented on Assets/Scripts/Guns/PlayerGuns/OctoBarrelLMG.cs
> +public class OctoBarrelLMG : Gun
Ditto Class Summary Comment

2022-06-21 22:56 UTC, toryjleo commented on Assets/Scripts/Guns/PlayerGuns/VulcanV64AutoCannons.cs
> +public class VulcanV64AutoCannons : Gun
Ditto class summary comment

2022-06-21 23:40 UTC, LiamMillerSE commented on Assets/Scripts/Bullets/VulkanV64Trail.cs
> +        Debug.Log("VULKAN FIRE!");
Commented out

2022-06-21 23:46 UTC, LiamMillerSE commented on Assets/Scripts/Guns/GunCrate.cs
> +public class GunCrate : MonoBehaviour
GunCrate was not supposed to be in SC. Removed this file

2022-06-24 00:24 UTC, toryjleo requested changes
Get error when running:

ArgumentNullException: Value cannot be null.
Parameter name: source
UnityEngine.AudioSource.Play () (at <8e2857b79be4468ca1c28dda75978191>:0)
VulcanV64AutoCannons.Shoot (UnityEngine.Vector3 initialVelocity) (at Assets/Scripts/Guns/PlayerGuns/VulcanV64AutoCannons.cs:48)
BikeScript.FixedUpdate () (at Assets/Scripts/Player/BikeScript.cs:90)

2022-06-26 11:52 UTC, toryjleo approved these changes
Cool! LGTM!

2022-06-26 12:52 UTC, merged