Ai death bug fix
toryjleo/BikeIdea pull request #62
Opened 2022-07-04 19:10 UTC by Tomerd-afk

Fixed AI so that effects of death are reset when they next spawn. Also added minor name changes

2022-07-04 19:11 UTC, Tomerd-afk commented on Assets/Scripts/AI/Ai.cs
>      }// this restets the enemies HP and sets them to alive;
This is the bulk of the fix
TODO: Add an interface for Animation state controllers in later PR

2022-07-05 21:11 UTC, toryjleo requested changes

2022-07-05 21:11 UTC, toryjleo commented on Assets/Scripts/AI/Ai.cs
> +    public Health hp;
remove trailing whitespace

2022-07-05 21:11 UTC, toryjleo commented on Assets/Scripts/AI/Ai.cs
> +    public float CurrentHP;
This appears to be unused

2022-08-11 23:58 UTC, Tomerd-afk reviewed
All set :shipit:

2022-08-12 20:43 UTC, toryjleo approved these changes

2022-08-14 16:52 UTC, merged