Car enemy + movement compoent
toryjleo/BikeIdea pull request #75
Opened 2022-09-19 22:12 UTC by Tomerd-afk

2022-09-19 22:42 UTC, toryjleo requested changes
There are further issues when I play this branch:

- The old non-vehicle enemies do not spawn in
- The car does not appear to move correctly, it rotates around awkwardly
- You can no longer touch the health pool

2022-09-19 22:42 UTC, toryjleo commented on Assets/Resources/AiClasses/CarAi.cs
> +
Ditto

2022-09-19 22:42 UTC, toryjleo commented on Assets/Resources/AiClasses/BikeAI.cs
> +
Please leave class comment

2022-09-19 22:42 UTC, toryjleo commented on Assets/Resources/AiClasses/CarAi.cs
> +    // Update is called once per frame
Please leave method comment

2022-09-19 22:42 UTC, toryjleo commented on Assets/Resources/AiClasses/CarAi.cs
> +    // Update is called once per frame
This is not "Update"

2022-09-19 22:42 UTC, toryjleo commented on Assets/Scripts/AI/MovementComponent.cs
> +public abstract class MovementComponent : MonoBehaviour
Ditto

2022-09-19 22:42 UTC, toryjleo commented on Assets/Scripts/AI/MovementComponent.cs
> +    public virtual void ApplyForces()
Please leave method comment

2022-09-19 22:42 UTC, toryjleo commented on Assets/TrackingScript.cs
> +public class TrackingScript : MonoBehaviour
Ditto

2022-09-22 00:37 UTC, Tomerd-afk commented
> *

What about the car movement do you want changed? Once I know I can fix it and update the PR

2022-09-22 19:49 UTC, toryjleo commented
> > 
> 
> What about the car movement do you want changed? Once I know I can fix it and update the PR

Upon further examination, I think it is good enough for the moment.

2022-09-27 20:12 UTC, toryjleo commented on Assets/Resources/AiClasses/CarAi.cs
> +public class CarAi : Ai
Please leave class comment

2022-09-27 20:12 UTC, toryjleo commented on Assets/Scripts/AI/CarMovementComponent.cs
> +public class CarMovementComponent : MovementComponent
Please leave class comment

2022-10-07 14:49 UTC, toryjleo approved these changes
LGTM :shipit:

2022-10-12 20:46 UTC, LiamMillerSE requested changes
Add the catch if needed, or merge without if not

2022-10-12 20:46 UTC, LiamMillerSE commented on Assets/Scripts/AI/Ai.cs
> +                animationStateController.TriggerDeathA();//TODO: add catch
Is this TODO for a future commit?

2022-10-13 17:03 UTC, Tomerd-afk commented
> Add the catch if needed, or merge without if not

merge without, the catch works for now

2022-11-05 17:26 UTC, closed without merging