Weapon abstract class
toryjleo/BikeIdea pull request #87
Opened 2022-11-15 01:09 UTC by Tomerd-afk

2022-11-15 20:15 UTC, toryjleo requested changes

2022-11-15 20:15 UTC, toryjleo commented on Assets/Scripts/Guns/Gun.cs
> -        bulletPool.DeInit();
This is never called now. Will cause bug. Please fix.

2022-11-15 20:15 UTC, toryjleo commented on Assets/Scripts/Guns/Weapon.cs
> +/// In the PR please list any aditional features you want for this class
Please remove "PR" comment. This sort of thing should be in the description of you PR

2022-11-16 01:52 UTC, LiamMillerSE submitted a review, later dismissed

2022-11-16 23:16 UTC, Tomerd-afk commented on Assets/Scripts/Guns/Weapon.cs
> +    //TODO: Add Code for Weapons and items being able to be picked up here!
Yes

2022-11-17 23:41 UTC, toryjleo approved these changes

2022-11-17 23:52 UTC, merged