CarAi now functional
toryjleo/BikeIdea pull request #93
Opened 2022-11-20 19:09 UTC by Tomerd-afk

I added back in the Car Ai as well as the movement component abstract class. This time in one merge.

2022-11-20 19:23 UTC, LiamMillerSE commented on Assets/Scripts/AI/CarAi.cs
> +
Looks good, just spacing format

2022-11-20 19:23 UTC, toryjleo requested changes

2022-11-20 19:23 UTC, toryjleo commented on Assets/Scripts/AI/CarAi.cs
> +    public float hitpoints
please move getter above methods

2022-11-20 19:23 UTC, toryjleo commented on Assets/Scripts/AI/CarAi.cs
> +
unneeded newlines. cleanup

2022-11-20 19:24 UTC, LiamMillerSE commented on Assets/Scripts/AI/MovementComponent.cs
> +    // Number of player hit points
Code missing or old comment

2022-11-20 19:24 UTC, LiamMillerSE approved these changes

2022-11-20 20:43 UTC, Tomerd-afk commented
Compiled Changes

2022-11-21 22:48 UTC, LiamMillerSE approved these changes

2022-11-24 15:01 UTC, toryjleo commented
:shipit:

2022-11-29 22:29 UTC, merged